### ISSUE TITLE
OMOP vs TrinetX cohorts are not comparable

### ISSUE THREAD

**Issue by vojtechhuser** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#112]
Looking at the SQL, the logic in OMOP is not using any encounter criteria.

Are we OK with the cohorts not being fully the same accross CDMs?

This logic in TrinetX is not in OMOP
![image](https://user-images.githubusercontent.com/7526119/87571182-a80ce480-c697-11ea-9a2f-38765ea54a67.png)

**Comment by kmkostka** [comment]
@vojtechhuser  An easy-to-read version of the OMOP phenotype can be found here: http://atlas-covid19.ohdsi.org/#/cohortdefinition/1148

The weak diagnosis occurring on the same visit is at this point:
![image](https://user-images.githubusercontent.com/44622115/87573808-7433be00-c69b-11ea-925d-d8fd8225b745.png)
![image](https://user-images.githubusercontent.com/44622115/87573881-8e6d9c00-c69b-11ea-86bb-0529945a4aab.png)

It's harder to trace through the SQL because the references occur in multiple places as the concepts are pulled, primary events are created and observation periods are constructed. The fastest way to find the 2 distinct occurrences if you look for the annotations that say "--Criteria Group" relating to the construction of the nested criteria for this logic.
