### ISSUE TITLE
cohort table seems to repeat person_id for each date instance

### ISSUE THREAD

**Issue by jphuong** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#125]
I use the R extractor and I was following up on some extraction issues that start once I run line 67, the runExtraction function. The EXTRACTION_VALIDATION.CSV output indicates that the there are duplications occurring, which I sourced back to the phenotype script and the creation of the cohort table (N3C_phenotype_omop_mssql.sql).

Since the tables are inner joining with the n3c_cohort table, somehow this table is a super long table and appears to duplicate person_id for each date instance, instead of a unique person_id for each row record. Line 738 in the phenotype script is when the n3c_cohort table starts to get created, but I think the startdate enddate fields have some mixed logic from the other tables. Perhaps, the start and end date logic just wasn't pivoted to represent earliest versus most recent date. The prior sections are not commented enough to distinguish when the focus is about event dates versus the cohort person_id records.

I'd appreciate any insights or feedback to fix the logic and create a person_id-level n3c_cohort table.

**Comment by rtmill** [comment]
Thank you for the helpful feedback. Start and end dates are a byproduct of pulling this code from what is generated by ATLAS and we never actually use either since the extract scripts only join on the person_id. The other data model scripts do not consider date and it appears we should not either, given the opportunity for duplication. @kmkostka thoughts?

i.e. when inserting into n3c_cohort, make the following change

From:
select distinct person_id, start_date, end_date

To:
select distinct person_id

**Comment by jphuong** [comment]
Thanks, @rtmill . I think that's how the cohort table was in prior versions. Given the new logic, I just want to verify that it wouldn't cause issues downstream. Thanks, again!

**Comment by kmkostka** [comment]
Technically speaking, the reason we tend to retain a record of start_date and end_date is because the way OHDSI defines a cohort doesn't restrict you from letting someone join multiple times if they meet your inclusion logic. In OHDSI thinking, a cohort is a set of persons who satisfy one or more inclusion criteria for a duration of time. 

Our current phenotype doesn't have any logic on "first ever occurrence" or anything imposed on follow up time so presumably the longer this project goes on, the more likely it is someone could qualify for our Phenotype definition multiple times. 

In a typical OHDSI study, we tend to retain the start_date and end_date to make it easier to add additional criteria to address this "the same person can be in a cohort multiple times" phenomenon.

Since N3C study designs are separate from the phenotype extraction logic (meaning an investigator may use their own phenotype definition when using the data in the Enclave), it's less important we call this out. So, a long answer of saying yes we can drop this but it's probably something to explain our eventual textbook @empfff .

**Comment by jphuong** [comment]
@kmkostka @rtmill - In Line 35, n3c_cohort is created with 3 columns, where the two dates are required as not null. So, this means I had to comment out the date columns in the CREATE TABLE statement in Line 35 and the SELECT statement in Line 759. Since then, the n3c_cohort table was correctly created and the extraction scripts was able to progress beyond the EXTRACTION_VALIDATION.CSV file and start extracting the tables.

**Comment by kmkostka** [comment]
Resolved in ````phenotype-21```` branch.
