### ISSUE TITLE
Community Issue: Want to help us test?

### ISSUE THREAD

**Issue by empfff** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#41]
If you are an ACT site using SQL Server, we would love to make sure the SQL Server versions of our ACT phenotype and extract code runs with no errors. If you are able to run one or both of the ACT phenotype scripts (path based and hardcoded) and the ACT extract script, drop us a comment with the results.

You'll have our gratitude!

**Comment by DarrenWHenderson** [comment]
This comment applies to N3C_phenotype_V1_4_act_mssql.sql:

This will not run without error as written on typical MSSQL installations. I have confirmed that a syntax error is thrown on SQL Server 2017 when executed directly from the github repo. 

`Msg 156, Level 15, State 1, Line 10
Incorrect syntax near the keyword 'select'.`
 
The Create Table as SELECT syntax applies only to the Azure Data Warehouse product version of SQL Server. This can be confirmed on the msdn library here: https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-as-select-azure-sql-data-warehouse?view=aps-pdw-2016-au7

For Standard/Enterprise Editions of SQL Server i.e. 2012, 2014, 2017 the appropriate syntax would incorporate a final SELECT INTO FROM the last common-table expression in the chain. So at the very end of the statment:

`select * into dbo.n3c_cohort from n3c_cohort` would suffice. 

I opted instead to create a view from your code, avoiding the need to refresh the cohort table on a schedule. I am a SQL Server DBA with 10+ years experience at the University of Kentucky CCTS. We have hosted i2b2 in both SQL Server and PostgreSQL, and I'm willing to help out anyway possible. 

I will also add, that on line 116 in the CTE covid_lab, and line 224 in the CTE covid_procedure, if you select observation_fact.patient_num here, instead of observation_fact.* the execution plan prepared (at least in my deployment) was much smarter, and dropped execution of the query from 3 minutes to 1 second. This may not effect anyone else. We are utilizing the clustered columnstore index in our deployment, so select * can be dangerous for performance when it decompresses the columnstores for no reason. Nothing else from the table aside from patient_num is ever used, so there's no reason to select * in either cte.

Thank you for your efforts.

**Comment by LisaOKeefe1** [comment]
Thank you so much for your feedback @DarrenWHenderson! We appreciate it.

**Comment by empfff** [comment]
@DarrenWHenderson This is exactly the kind of feedback we were hoping for! I have made the changes that you noted and pushed the new code to the repo. You have our thanks!

**Comment by DarrenWHenderson** [comment]
Happy to help.
