### ISSUE TITLE
OMOP phenotype dx code handling

### ISSUE THREAD

**Issue by empfff** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#73]
Noticed by @LoraLingrey-TriNetX : There is no special handling for B97.21 and B97.29 included in the OMOP phenotype code; those are our dxs that are treated differently (weak/strong) based on date. There is no reference to 4/1/2020 in the OMOP code.

**Comment by kmkostka** [comment]
These codes map to:
- B97.21 (SARS-associated coronavirus as the cause of diseases classified elsewhere) maps to SNOMED 398447004 (Severe acute respiratory syndrome)
- B97.29 (Other coronavirus as the cause of diseases classified elsewhere) maps to SNOMED 27619001 (Disease due to Coronaviridae)

The logic will be reviewed and updated. New scripts will be regenerated. 

Do we want to add these SNOMEDs to the list with the same date-time distinction?

**Comment by kmkostka** [comment]
[Phenotype script ](https://github.com/National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition/blob/master/PhenotypeScripts/N3C_phenotype_omop_mssql.sql)and JSONs are updated.

@rtmill  can you double check my work on the mssqlserver script? If kosher, we can run through JAR.

**Comment by kmkostka** [comment]
Validated. We can close.
