### ISSUE TITLE
Couple small R exporter things

### ISSUE THREAD

**Issue by empfff** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#77]
I had a chance to run the R exporter on our Oracle test instance of OMOP. Two things--one bug, one possible documentation fix:

1. Depending on the version of R you have, you may have a problem using the "remotes" package, which by default causes installs to fail if there are warning messages (which versioning causes a lot of). To force it through, a second environment variable in addition to JAVA_HOME must be set: R_REMOTES_NO_ERRORS_FROM_WARNINGS = true. @rtmill I am happy to add this to the documentation in case others experience this, but wanted to get your take first.

2. Even though the execution part of the script allows the user to change their output directory from the default, the default output folder is actually set in the underlying function definition and won't override. So, the way it is now, the extracted files will always export to the default location.

Other than these minor things, works great!

**Comment by rtmill** [comment]
1. Sounds good. I would side with highly recommending that they upgrade to the latest version of R (4.0.0) and if that isn't possible use the environment variable workaround. Sweeping errors under the carpet seems like it could complicate debugging efforts down the road

2. This was discussed previously. Although the output directory appears to be hardwired in the underlying function, it is not. I believe the issue is that the function calls in the example execution and documentation do not provide a value for the (optional) parameter so during execution it uses the default value (/output/ of the working directory). I'll push an edit to the docs.
