### ISSUE TITLE
other codes to consider for inclusion

### ISSUE THREAD

**Issue by jovo** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#84]
- B97.2 as a weak positive (at least before 4/1/20) because it likely comes up in Epic when typing Coronavirus
- U07.2 as a weak positive

**Comment by LisaOKeefe1** [comment]
Thank you @jovo !

**Comment by empfff** [comment]
Thank you for this feedback! We considered these codes early in the phenotyping process; here are the reasons for non-inclusion:

U07.2: In ICD-10, but not ICD-10-CM, so will never be used in the US.
B97.2: We noticed the same thing! (that it comes up in Epic when typing coronavirus.) For that reason, we did have this code in the first version of the phenotype. However, it fell out after community review because there were fears that it would result in too many false positives.

Thank you for this feedback, and please keep it coming! We had considered these particular codes, but you very well could come up with more that we've never seen, next time. :)
