### ISSUE TITLE
Lab Test List and LOINC for non-COVID SARS nucleic acid testing

### ISSUE THREAD

**Issue by pambanning** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#94]
Regarding the Latest Phenotype and list of LOINCs for the lab tests.....The in vitro kit manufacturers had included some SARS-like and SARS-related detection by nucleic acid, in anticipation of SARS-CoV-2 virus mutating. Regenstrief included the build of LOINCs for those non-COVID19 organisms. I'm seeing them listed in the LOINC Lab Code lists of the Latest Phenotype. Would suggest a discussion on the pertinence of their inclusion? If it's decided that ALL of the LOINCs stay in the phenotype, may i suggest we delineate the specific COVID19 positive paths.

**Comment by empfff** [comment]
@pambanning would you be able to list the LOINCs that fall into this category?

**Comment by pambanning** [comment]
@empfff sorry for the delay. Here is a broad list of coronavirus tests that are NOT specific to SARS-COV-2. This is from the June 17, 2020 release of LOINC 2.68. An intersect with the LOINC Lab Code lists at N3C will dial in the focus.
[N3C SARS-like LOINCs to discuss exclusion.xlsx](https://github.com/National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition/files/5084839/N3C.SARS-like.LOINCs.to.discuss.exclusion.xlsx)

**Comment by empfff** [comment]
Thank you @pambanning ! Very helpful indeed.

**Comment by empfff** [comment]
These changes will take effect in the phenotype released today (2.2). Thanks again for your feedback!

**Comment by cgchute** [comment]
i would challenge this.  There are two recognized non-COVID, serious SARS family infections in humans: 1. MERS, 2. the original SARS.  The epidemiology of these conditions is clear;  the Hong Kong SARS epidemic was about 1000 people - ever.  MERS has affected about 2,500 people, ever.  The number of people in the US diagnosed with SARS or MERS over the past five years is probably 0, might be 1.   So, the risk of misclassifying SARS variants as something other than COVID is 0, with probably 8 9's of confidence.  I would restore those non-specific SARS codes, and they are certainly reflection COVID cases and are probably attributable to the lab picking the wrong LOIINC code rather than those tests are not COVID.
